version: '2'
services:
    twentyonepointsreact-app:
        image: twentyonepointsreact
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://twentyonepointsreact-mysql:3306/twentyonepointsreact?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=twentyonepointsreact-elasticsearch:9300
        ports:
            - 8080:8080
    twentyonepointsreact-mysql:
        extends:
            file: mysql.yml
            service: twentyonepointsreact-mysql
    twentyonepointsreact-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: twentyonepointsreact-elasticsearch
